/** Auto-generated by scripts/optimize-bg.mjs — do not edit manually */
export const BG_PLACEHOLDERS = {
  "console": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABwBACdASoQABwAPzmEuVOvKKWisAgB4CcJaACdAywBinE08mNuvYwEfaUgAAD+u6XeQf7A2JjxaKvQYdKVPX1jTWMFbnnJ6UDGohvPMyOhQn890kZMcsfY+eGd7lbBY+uXXLnpntIoGTtX8kFirhpg8MhvbBaWpxPNeL0wcdIwU2QQFbVgEMJOo8bFbGh7zk5YRRAA",
  "explorer": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQABAABUB8JbACdAEOpCfe+QAA/vKh2rv85rg6R9k2VTyn/zklYVtO+3mvkcmyRa1uxqt4PAAAAA==",
  "logo": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwAgCdASoQAAcABUB8JaACdAEfmpkBCUwlAAD9u7WldK5ikNnf77fdtSJox1m897l80YEWABcq9yV2s2USCG6UZalKQmPLe03ODfIrP78AAA=="
} as const;

export const LOGO_DIMENSIONS = {
  "width": 768,
  "height": 314
} as const;
