import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import sharp from 'sharp';

const __dirname = dirname(fileURLToPath(import.meta.url));
const publicDir = join(__dirname, '..', 'public');
const outTs = join(__dirname, '..', 'src', 'lib', 'bg-placeholders.ts');

const assets = [
  { jpg: 'a7.png', webp: 'a7.webp', key: 'console' },
  { jpg: 'a4.jpg', webp: 'a4.webp', key: 'explorer' },
];

const placeholders = {};
let logoDimensions = null;

for (const { jpg, webp, key } of assets) {
  const input = join(publicDir, jpg);
  const output = join(publicDir, webp);
  await sharp(input)
    .resize(1440, null, { withoutEnlargement: true })
    .webp({ quality: 75 })
    .toFile(output);

  const blurBuf = await sharp(input).resize(16).webp({ quality: 20 }).toBuffer();
  placeholders[key] = `data:image/webp;base64,${blurBuf.toString('base64')}`;
  console.log(`Optimized ${jpg} -> ${webp}`);
}

const logoInput = join(publicDir, 'cp-logo.png');
const { data: logoData, info: logoInfo } = await sharp(logoInput)
  .trim({ threshold: 15 })
  .resize(768, null, { withoutEnlargement: true })
  .toBuffer({ resolveWithObject: true });

logoDimensions = { width: logoInfo.width, height: logoInfo.height };

await sharp(logoData).webp({ quality: 82 }).toFile(join(publicDir, 'cp-logo.webp'));
await sharp(logoData)
  .png({ compressionLevel: 9, palette: false })
  .toFile(join(publicDir, 'cp-logo.png'));

const logoBlurBuf = await sharp(logoData).resize(16).webp({ quality: 20 }).toBuffer();
placeholders.logo = `data:image/webp;base64,${logoBlurBuf.toString('base64')}`;
console.log(`Optimized cp-logo.png -> cp-logo.webp (${logoInfo.width}x${logoInfo.height})`);

const ts = `/** Auto-generated by scripts/optimize-bg.mjs — do not edit manually */
export const BG_PLACEHOLDERS = ${JSON.stringify(placeholders, null, 2)} as const;

export const LOGO_DIMENSIONS = ${JSON.stringify(logoDimensions, null, 2)} as const;
`;
writeFileSync(outTs, ts);
console.log('Wrote src/lib/bg-placeholders.ts');
